### ISSUE TITLE
SB-control-flows-WIP.json V0.0.1 

### ISSUE THREAD

**Issue by dlindh** [sonnen-tools/node-red#2]
Tried it out. Not sure if I am missing stuff but I get some other views then the release notes.

Set the price value high to get some data.

There seems to be some chargeing hours found. 
![image](https://github.com/sonnen-tools/node-red/assets/2614783/e8100628-5b88-4ec1-ad23-3ca9c8b7475b)

But the webpage shows nothing of that sort.
![image](https://github.com/sonnen-tools/node-red/assets/2614783/829048be-60d7-4dc5-8c76-6c5d38cbed7f)

Is there some additional stuff that needs to be done?

I get some json error in the debug as well.

![image](https://github.com/sonnen-tools/node-red/assets/2614783/bfdc6ddf-2b7d-4479-8ffc-13521e401462)

**Comment by markusjnagel** [comment]
Hm, it seems one of the calls to the Sonnenbatterie fails (this is where I use the "generic http request" that then calls the Sonnenbatterie. 

I _think_ it could be related to your API settings.... the debug node returns the HTML for a 404 (not found) error, so it means the IP for your Sonnenbatterie is set correctly.

Can you login to your Sonnenbatterie and check if the API access has been switched on (both read and write)? 
https://github.com/sonnen-tools/node-red/blob/main/docs/configuration.md#sonnen_api_token

![image](https://github.com/sonnen-tools/node-red/assets/33287465/8007e709-e66a-42bd-bd46-898101b3d07a)

**Comment by dlindh** [comment]
Api is enabled, see below ![image](https://github.com/sonnen-tools/node-red/assets/2614783/043072e2-1eb4-4c1d-baa4-1fae415bb913) and we also have the same software version on the battery so I gues the api should be the same. 

Double checked everything under SonnenBattery settings and it looks ok. Is it possible to know what specific request this is? Then I can try it using curl just to verify :)

**Comment by dlindh** [comment]
Running manually works fine (found it after digging around)

root@webbox:~# curl -X GET -H 'Content-Length: 0' --header "Auth-Token: TOKEN" http://192.168.0.142/api/v2/status

{"BackupBuffer":"10","BatteryCharging":false,"BatteryDischarging":false,"Consumption_Avg":5101,"Consumption_W":5104,"Fac":49.99599838256836,"FlowConsumptionBattery":false,"FlowConsumptionGrid":true,"FlowConsumptionProduction":false,"FlowGridBattery":false,"FlowProductionBattery":false,"FlowProductionGrid":false,"GridFeedIn_W":-5107,"IsSystemInstalled":1,"OperatingMode":"1","Pac_total_W":0,"Production_W":0,"RSOC":36,"RemainingCapacity_Wh":15597,"SystemStatus":"OnGrid","Timestamp":"2024-01-07 12:25:23","USOC":30,"Uac":227,"Ubat":210,"dischargeNotAllowed":false,"generator_autostart":false}root@webbox:~#

**Comment by dlindh** [comment]
Re added the flow as new set it up again and now i works..

**Comment by markusjnagel** [comment]
> Re added the flow as new set it up again and now i works..   

huh...  reminds me of: 

https://youtu.be/nn2FB1P_Mn8?si=_J815xgIvLtY8pRG  ;-) 

Nevertheless, glad it works now. The miracles of modern technology....

**Comment by dlindh** [comment]
Haha, well it was as we say in sweden skit bakom tangentbordet. The request was actually sent to my printer instead of the battery :)
