### ISSUE TITLE
Bad Request!

### ISSUE THREAD

**Issue by froemer4773** [sonnen-tools/node-red#3]
I get an error on the Notify Node, do you know what it is?

`{"errors":[{"message":"Syntax Error: Unterminated string.","extensions":{"code":"GRAPHQL_PARSE_FAILED"}}],"httpCode":400,"statusCode":400,"statusMessage":"Bad Request"}`

Here is the OUTPUT from the storeAllPrices node:

`{"viewer":{"homes":[{"currentSubscription":{"priceInfo":{"today":[{"total":0.3007,"startsAt":"2024-01-06T00:00:00.000+01:00"},{"total":0.2982,"startsAt":"2024-01-06T01:00:00.000+01:00"},{"total":0.2934,"startsAt":"2024-01-06T02:00:00.000+01:00"},{"total":0.2897,"startsAt":"2024-01-06T03:00:00.000+01:00"},{"total":0.2897,"startsAt":"2024-01-06T04:00:00.000+01:00"},{"total":0.2916,"startsAt":"2024-01-06T05:00:00.000+01:00"},{"total":0.2922,"startsAt":"2024-01-06T06:00:00.000+01:00"},{"total":0.2996,"startsAt":"2024-01-06T07:00:00.000+01:00"},{"total":0.308,"startsAt":"2024-01-06T08:00:00.000+01:00"},{"total":0.3125,"startsAt":"2024-01-06T09:00:00.000+01:00"},{"total":0.3186,"startsAt":"2024-01-06T10:00:00.000+01:00"},{"total":0.3223,"startsAt":"2024-01-06T11:00:00.000+01:00"},{"total":0.3208,"startsAt":"2024-01-06T12:00:00.000+01:00"},{"total":0.3161,"startsAt":"2024-01-06T13:00:00.000+01:00"},{"total":0.3129,"startsAt":"2024-01-06T14:00:00.000+01:00"},{"total":0.3159,"startsAt":"2024-01-06T15:00:00.000+01:00"},{"total":0.3216,"startsAt":"2024-01-06T16:00:00.000+01:00"},{"total":0.3269,"startsAt":"2024-01-06T17:00:00.000+01:00"},{"total":0.3261,"startsAt":"2024-01-06T18:00:00.000+01:00"},{"total":0.3206,"startsAt":"2024-01-06T19:00:00.000+01:00"},{"total":0.3124,"startsAt":"2024-01-06T20:00:00.000+01:00"},{"total":0.3075,"startsAt":"2024-01-06T21:00:00.000+01:00"},{"total":0.3058,"startsAt":"2024-01-06T22:00:00.000+01:00"},{"total":0.2978,"startsAt":"2024-01-06T23:00:00.000+01:00"}],"tomorrow":[{"total":0.3028,"startsAt":"2024-01-07T00:00:00.000+01:00"},{"total":0.2978,"startsAt":"2024-01-07T01:00:00.000+01:00"},{"total":0.2941,"startsAt":"2024-01-07T02:00:00.000+01:00"},{"total":0.2902,"startsAt":"2024-01-07T03:00:00.000+01:00"},{"total":0.2883,"startsAt":"2024-01-07T04:00:00.000+01:00"},{"total":0.2886,"startsAt":"2024-01-07T05:00:00.000+01:00"},{"total":0.2919,"startsAt":"2024-01-07T06:00:00.000+01:00"},{"total":0.2952,"startsAt":"2024-01-07T07:00:00.000+01:00"},{"total":0.3001,"startsAt":"2024-01-07T08:00:00.000+01:00"},{"total":0.3038,"startsAt":"2024-01-07T09:00:00.000+01:00"},{"total":0.3065,"startsAt":"2024-01-07T10:00:00.000+01:00"},{"total":0.3089,"startsAt":"2024-01-07T11:00:00.000+01:00"},{"total":0.3083,"startsAt":"2024-01-07T12:00:00.000+01:00"},{"total":0.3037,"startsAt":"2024-01-07T13:00:00.000+01:00"},{"total":0.3032,"startsAt":"2024-01-07T14:00:00.000+01:00"},{"total":0.3075,"startsAt":"2024-01-07T15:00:00.000+01:00"},{"total":0.314,"startsAt":"2024-01-07T16:00:00.000+01:00"},{"total":0.3239,"startsAt":"2024-01-07T17:00:00.000+01:00"},{"total":0.3276,"startsAt":"2024-01-07T18:00:00.000+01:00"},{"total":0.326,"startsAt":"2024-01-07T19:00:00.000+01:00"},{"total":0.3224,"startsAt":"2024-01-07T20:00:00.000+01:00"},{"total":0.3138,"startsAt":"2024-01-07T21:00:00.000+01:00"},{"total":0.3113,"startsAt":"2024-01-07T22:00:00.000+01:00"},{"total":0.3026,"startsAt":"2024-01-07T23:00:00.000+01:00"}]}}}]},"title":"Updated prices for tomorrow!","screen":"HOME","message":"Low: 0.29\nHigh: 0.33\nAverage: 0.31\nMaxPrice for charging: 0.25\n0 slots for charging identified"}`

**Comment by markusjnagel** [comment]
Yeah, I'm sorry, I fixed that in V0.0.1 WIP, but not the "release" version yet. I'll leave this open until I have pushed the release.

**Comment by markusjnagel** [comment]
Hey Steffen, I just created the [v0.0.2 release](https://github.com/sonnen-tools/node-red/releases) that solves the problem.
